alter table public.profiles
  add column if not exists vip_until timestamp with time zone,
  add column if not exists vip_source text,
  add column if not exists vip_granted_at timestamp with time zone,
  add column if not exists referral_code text,
  add column if not exists referral_vip_granted_at timestamp with time zone;

update public.profiles
set referral_code = 'u' || substr(replace(id::text, '-', ''), 1, 10)
where referral_code is null;

alter table public.profiles
  alter column referral_code set default ('u' || substr(replace(gen_random_uuid()::text, '-', ''), 1, 10));

create unique index if not exists profiles_referral_code_key
  on public.profiles (referral_code);

create table if not exists public.referral_visits (
  id bigint generated by default as identity primary key,
  referrer_id uuid not null references public.profiles(id) on delete cascade,
  visitor_hash text not null,
  visitor_id_hint text,
  user_agent_hash text,
  ip_hash text,
  credited boolean not null default true,
  created_at timestamp with time zone not null default now(),
  unique (referrer_id, visitor_hash)
);

create index if not exists referral_visits_referrer_created_idx
  on public.referral_visits (referrer_id, created_at desc);

alter table public.referral_visits enable row level security;

revoke all on public.referral_visits from anon, authenticated;
grant select, insert, update, delete on public.referral_visits to service_role;
grant usage, select on sequence public.referral_visits_id_seq to service_role;

create schema if not exists app_private;
revoke all on schema app_private from public, anon, authenticated;

create or replace function app_private.protect_profile_system_columns()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  jwt_role text := current_setting('request.jwt.claim.role', true);
  actor_is_admin boolean := false;
begin
  if jwt_role = 'service_role' then
    return new;
  end if;

  if auth.uid() is not null then
    select coalesce(p.is_admin, false)
      into actor_is_admin
      from public.profiles p
      where p.id = auth.uid();
  end if;

  if actor_is_admin then
    return new;
  end if;

  if new.is_admin is distinct from old.is_admin
    or new.is_banned is distinct from old.is_banned
    or new.ban_reason is distinct from old.ban_reason
    or new.ban_until is distinct from old.ban_until
    or new.post_count is distinct from old.post_count
    or new.vip_until is distinct from old.vip_until
    or new.vip_source is distinct from old.vip_source
    or new.vip_granted_at is distinct from old.vip_granted_at
    or new.referral_code is distinct from old.referral_code
    or new.referral_vip_granted_at is distinct from old.referral_vip_granted_at
  then
    raise exception 'protected_profile_columns';
  end if;

  return new;
end;
$$;

drop trigger if exists protect_profile_system_columns on public.profiles;
create trigger protect_profile_system_columns
  before update on public.profiles
  for each row execute function app_private.protect_profile_system_columns();
